language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy .
  - docker build -t udagram-api-user .
  - docker build -t udagram-api-feed .
  - docker build -t udagram-frontend .
  - docker tag reverseproxy azumahjohsua/reverseproxy
  - docker tag udagram-api-user azumahjohsua/reverseproxy
  - docker tag udagram-api-feed azumahjohsua/reverseproxy
  - docker tag udagram-frontend azumahjohsua/reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push azumahjoshua/reverseproxy
  - docker push azumahjoshua/udagram-api-user
  - docker push azumahjoshua/udagram-api-feed
  - docker push azumahjoshua/udagram-frontend
