apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-uuser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: azumahjoshua/udagram-api-user:v1
        ports:
           - containerPort: 8080
        envFrom:
           - configMapRef:
              name: azumahjoshuaproject3config
           - secretRef:
              name: azumahjoshuasecret